name: BingX Grid — Capture OUT (manual, v9)

on:
  workflow_dispatch:

concurrency:
  group: bingx-grid-capture
  cancel-in-progress: true

env:
  PY_VERSION: "3.11"

  MIN_RANGE: "1.0"
  MAX_DRIFT: "0.40"
  MAX_CV:   "0.60"
  MIN_SCORE: "25"

  FB_MIN_SCORE: "40"
  FB_MAX_CV:    "0.60"
  FB_MAX_DRIFT: "0.40"

jobs:
  scan-and-filter:
    strategy:
      matrix:
        tf: ["5m","15m","1h"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          chmod +x run_scan_muted_bingx.sh || true

      - name: Run silent scan with Telegram capture (${{ matrix.tf }})
        env:
          BOT_TOKEN: "0"
          CHAT_ID:  "0"
        run: ./run_scan_muted_bingx.sh ${{ matrix.tf }}

      - name: Filter Wide Range Candidates (${{ matrix.tf }})
        run: |
          TF="${{ matrix.tf }}"
          FTF="$TF"; if [ "$TF" = "5m" ]; then FTF="3m"; fi
          echo "Using filter timeframe: $FTF (from TF=$TF)"
          python grid_filter.py scan_${TF}.txt             --tf "$FTF"             --min-range $MIN_RANGE             --max-drift $MAX_DRIFT             --max-cv $MAX_CV             --min-score $MIN_SCORE             --fb-min-score $FB_MIN_SCORE             --fb-max-cv $FB_MAX_CV             --fb-max-drift $FB_MAX_DRIFT             --top 24             --print-okx | tee filtered_${TF}.txt

      - name: Send Telegram (only if candidates) — ${{ matrix.tf }}
        if: always()
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:  ${{ secrets.CHAT_ID }}
        run: |
          if grep -q "OKX ▶[[:space:]]*Lower=" "filtered_${{ matrix.tf }}.txt"; then
            python telegram_notify.py "filtered_${{ matrix.tf }}.txt" "${{ matrix.tf }}"
          else
            echo "No candidates; no Telegram."
          fi

      - name: Upload artifacts (${{ matrix.tf }})
        uses: actions/upload-artifact@v4
        with:
          name: bingx-grid-capture-${{ matrix.tf }}-${{ github.run_id }}
          path: |
            scan_${{ matrix.tf }}.txt
            filtered_${{ matrix.tf }}.txt
