name: BingX Grid Scan

on:
  schedule:
    - cron: '12 * * * *'   # Her saat :12'de çalışır
  workflow_dispatch: {}

jobs:
  run-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run BingX Grid Scan
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TOP_K: ${{ vars.TOP_K }}
          ATR_PCT_MIN: ${{ vars.ATR_PCT_MIN }}
          RANGE_PCT_MIN: ${{ vars.RANGE_PCT_MIN }}
          ADX_MAX: ${{ vars.ADX_MAX }}
          MID_CROSS_MIN: ${{ vars.MID_CROSS_MIN }}
          DRIFT_MAX_RATIO: ${{ vars.DRIFT_MAX_RATIO }}
          MIN_QVOL_USDT: ${{ vars.MIN_QVOL_USDT }}
          LISTED_MIN_DAYS: ${{ vars.LISTED_MIN_DAYS }}
          MIN_GRID_K_ATR: ${{ vars.MIN_GRID_K_ATR }}
        run: |
          python scan_bingx_grid.py
