name: Bot Diagnostics (CLI & Code Scan)

on:
  workflow_dispatch:

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run diagnostics
        shell: bash
        run: |
          chmod +x scripts/diag.sh || true
          bash scripts/diag.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-diagnostics
          path: diag.txt
