name: Hybrid Paper Bot

on:
  workflow_dispatch:
    inputs:
      RUN_SECONDS:
        description: "Çalışma süresi (saniye)"
        required: false
        default: "0"

jobs:
  paper:
    runs-on: ubuntu-latest
    timeout-minutes: 45   # sabit güvenlik limiti, kod zaten RUN_SECONDS ile bitecek

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run paper bot
        env:
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_API_SECRET: ${{ secrets.BINGX_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SYMBOL: ${{ vars.SYMBOL }}
          GRID_LEVELS: ${{ vars.GRID_LEVELS }}
          GRID_CAPITAL: ${{ vars.GRID_CAPITAL }}
          ATR_K: ${{ vars.ATR_K }}
          RETUNE_SEC: ${{ vars.RETUNE_SEC }}
          MAX_OPEN_NOTIONAL: ${{ vars.MAX_OPEN_NOTIONAL }}
          MAX_SYMBOL_EXPOSURE: ${{ vars.MAX_SYMBOL_EXPOSURE }}
          DAILY_MAX_LOSS: ${{ vars.DAILY_MAX_LOSS }}
          STOP_PCT: ${{ vars.STOP_PCT }}
          FEE: ${{ vars.FEE }}
          TRI_EDGE_MIN: ${{ vars.TRI_EDGE_MIN }}
          ADX_LIMIT_HI: ${{ vars.ADX_LIMIT_HI }}
          ADX_LIMIT_LO: ${{ vars.ADX_LIMIT_LO }}
          GUARD_COOLDOWN_SEC: ${{ vars.GUARD_COOLDOWN_SEC }}
          GUARD_CONSEC_N: ${{ vars.GUARD_CONSEC_N }}
          VOL_SPIKE_FAST: ${{ vars.VOL_SPIKE_FAST }}
          VOL_SPIKE_SLOW: ${{ vars.VOL_SPIKE_SLOW }}
          VOL_SPIKE_MULT: ${{ vars.VOL_SPIKE_MULT }}
          CCXT_TIMEOUT_MS: ${{ vars.CCXT_TIMEOUT_MS }}
          RUN_SECONDS: ${{ github.event.inputs.RUN_SECONDS || 0 }}
          DRY_RUN: 1
        run: |
          echo "Run seconds: $RUN_SECONDS"
          python -m src.runner.paper_bot
