name: Hybrid Paper Bot

on:
  workflow_dispatch:
    inputs:
      RUN_SECONDS:
        description: "Çalışma süresi (saniye)"
        required: false
        default: "0"

jobs:
  paper:
    runs-on: ubuntu-latest
    timeout-minutes: 45   # sabit güvenlik limiti, kod zaten RUN_SECONDS ile bitecek

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run paper bot
        env:
          SYMBOL:               ${{ vars.SYMBOL || 'BTC/USDT:USDT' }}
          GRID_LEVELS:          ${{ vars.GRID_LEVELS || 16 }}
          GRID_CAPITAL:         ${{ vars.GRID_CAPITAL || 200 }}
          ATR_K:                ${{ vars.ATR_K || 1.2 }}
          RETUNE_SEC:           ${{ vars.RETUNE_SEC || 120 }}

          MAX_OPEN_NOTIONAL:    ${{ vars.MAX_OPEN_NOTIONAL || 1000 }}
          MAX_SYMBOL_EXPOSURE:  ${{ vars.MAX_SYMBOL_EXPOSURE || 500 }}
          DAILY_MAX_LOSS:       ${{ vars.DAILY_MAX_LOSS || 200 }}
          STOP_PCT:             ${{ vars.STOP_PCT || 0.03 }}

          FEE:                  ${{ vars.FEE || 0.0006 }}
          TRI_EDGE_MIN:         ${{ vars.TRI_EDGE_MIN || 0.0015 }}

          ADX_LIMIT_HI:         ${{ vars.ADX_LIMIT_HI || 35 }}
          ADX_LIMIT_LO:         ${{ vars.ADX_LIMIT_LO || 28 }}
          GUARD_COOLDOWN_SEC:   ${{ vars.GUARD_COOLDOWN_SEC || 60 }}
          GUARD_CONSEC_N:       ${{ vars.GUARD_CONSEC_N || 3 }}

          VOL_SPIKE_FAST:       ${{ vars.VOL_SPIKE_FAST || 20 }}
          VOL_SPIKE_SLOW:       ${{ vars.VOL_SPIKE_SLOW || 120 }}
          VOL_SPIKE_MULT:       ${{ vars.VOL_SPIKE_MULT || 2.0 }}

          CCXT_TIMEOUT_MS:      ${{ vars.CCXT_TIMEOUT_MS || 15000 }}
          RUN_SECONDS:          ${{ github.event.inputs.RUN_SECONDS || 0 }}
          DRY_RUN:              1
        run: |
          echo "Run seconds: $RUN_SECONDS"
          python -m src.runner.paper_bot
