name: OKX Grid — Broad Scan & Filter

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

env:
  PY_VERSION: "3.11"
  MIN_RANGE: "2.5"
  MAX_DRIFT: "0.20"
  MAX_CV: "0.35"
  MIN_SCORE: "45"
  FB_MIN_SCORE: "50"
  FB_MAX_CV: "0.40"
  FB_MAX_DRIFT: "0.30"
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  scan-and-filter:
    strategy:
      matrix:
        tf: ["3m","5m","15m"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            python -V
          fi
          chmod +x run_scan_matrix.sh

      - name: Run broad scan matrix (${{ matrix.tf }})
        shell: bash
        run: ./run_scan_matrix.sh ${{ matrix.tf }}

      - name: Filter Wide Range Candidates (${{ matrix.tf }})
        shell: bash
        run: |
          python grid_filter.py scan_${{ matrix.tf }}.txt                 --tf ${{ matrix.tf }}                 --min-range $MIN_RANGE                 --max-drift $MAX_DRIFT                 --max-cv $MAX_CV                 --min-score $MIN_SCORE                 --fb-min-score $FB_MIN_SCORE                 --fb-max-cv $FB_MAX_CV                 --fb-max-drift $FB_MAX_DRIFT                 --top 16                 --print-okx | tee filtered_${{ matrix.tf }}.txt

      - name: Upload artifacts (${{ matrix.tf }})
        uses: actions/upload-artifact@v4
        with:
          name: okx-grid-${{ matrix.tf }}-${{ github.run_id }}
          path: |
            scan_${{ matrix.tf }}.txt
            filtered_${{ matrix.tf }}.txt
