name: Secrets Presence Check

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    # Map the secrets you *expect* into env vars so we can check SET/MISSING safely.
    # Edit the list below to match your repo's needs.
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
      OKX_API_KEY: ${{ secrets.OKX_API_KEY }}
      OKX_SECRET: ${{ secrets.OKX_SECRET }}
      OKX_PASSPHRASE: ${{ secrets.OKX_PASSPHRASE }}
      BYBIT_HOSTS: ${{ secrets.BYBIT_HOSTS }}
      PROXY_URL: ${{ secrets.PROXY_URL }}
      RATE_LIMIT: ${{ secrets.RATE_LIMIT }}
      # Add more here as needed, e.g.:
      # SOME_OTHER_KEY: ${{ secrets.SOME_OTHER_KEY }}

    steps:
      - name: Print secret presence (no values leaked)
        shell: bash
        run: |
          set -euo pipefail
          echo "Checking secrets presence (printing only SET/MISSING)..."
          NAMES=(
            "BOT_TOKEN" "CHAT_ID"
            "OKX_API_KEY" "OKX_SECRET" "OKX_PASSPHRASE"
            "BYBIT_HOSTS" "PROXY_URL" "RATE_LIMIT"
          )
          missing=0
          for v in "${NAMES[@]}"; do
            if [ -z "${!v-}" ]; then
              echo "$v: MISSING"
              missing=$((missing+1))
            else
              echo "$v: SET"
            fi
          done
          echo "-----"
          if [ "$missing" -gt 0 ]; then
            echo "Some secrets are MISSING. Add them in Settings → Secrets and variables → Actions."
          else
            echo "All listed secrets are SET."
          fi
